/**
 * @file fx5.h
 * @brief Public API for a minimal Mitsubishi FX5 SLMP binary communication library.
 *
 * This library provides a small, allocation-free API for building FX5 requests
 * and parsing FX5 responses over TCP using SLMP binary frames.
 *
 * Supported features:
 * - Batch read
 * - Batch write
 * - Devices: D, M, X, Y, L, F, S, B, W, SM, SD, SB, SW
 * - Request build in 4E binary by default, optionally 3E binary
 * - Response parsing with automatic 3E/4E frame detection
 *
 * Not supported:
 * - Serial communication
 * - ASCII protocol variants
 * - Dynamic memory allocation
 *
 * The library is not thread-safe.
 */

#ifndef FX5_H
#define FX5_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>

#include <fx5/fx5_layout.h>

/** @defgroup fx5_public Public API
 *  @brief Public API for applications using the FX5 library.
 *  @{ */

/**
 * @def FX5_MAX_VALUE_COUNT
 * @brief Number of 16-bit value storage slots in a context.
 *
 * It is a compile-time storage limit of this library, not an SLMP or FX5 PLC
 * protocol limit.
 *
 * For word devices, one storage slot stores one logical value. For bit devices,
 * one storage slot stores 16 logical bit values, so the maximum bit-device
 * request count is @ref FX5_MAX_BIT_VALUE_COUNT.
 *
 * The default keeps each context small for embedded/static allocation use.
 * Define FX5_MAX_VALUE_COUNT before including this header, or pass a compiler
 * definition such as -DFX5_MAX_VALUE_COUNT=128, to trade more RAM for larger
 * word and bit batch read/write transactions.
 */
#ifndef FX5_MAX_VALUE_COUNT
#define FX5_MAX_VALUE_COUNT (32u)
#endif

#if FX5_MAX_VALUE_COUNT == 0
#error "FX5_MAX_VALUE_COUNT must be greater than zero"
#endif

#if FX5_MAX_VALUE_COUNT > 4095
#error "FX5_MAX_VALUE_COUNT must be <= 4095 because public value counts are uint16_t"
#endif

/** @brief Maximum logical values per word-device transaction. */
#define FX5_MAX_WORD_VALUE_COUNT (FX5_MAX_VALUE_COUNT)

/** @brief Maximum logical values per bit-device transaction. */
#define FX5_MAX_BIT_VALUE_COUNT  ((uint16_t)((uint32_t)FX5_MAX_VALUE_COUNT * 16u))

/** @brief Maximum word-device payload bytes stored by one context. */
#define FX5_MAX_WORD_PAYLOAD_BYTES ((uint16_t)((uint32_t)FX5_MAX_WORD_VALUE_COUNT * 2u))

/** @brief Maximum bit-device payload bytes stored by one context. */
#define FX5_MAX_BIT_PAYLOAD_BYTES  ((uint16_t)((FX5_MAX_BIT_VALUE_COUNT + 1u) / 2u))

/**
 * @def FX5_CONTEXT_POOL_SIZE
 * @brief Number of internal context instances available in the static pool.
 *
 * Increase this value if multiple FX5 devices or concurrent transactions
 * must be handled by separate contexts.
 */
#ifndef FX5_CONTEXT_POOL_SIZE
#define FX5_CONTEXT_POOL_SIZE (2u)
#endif

#if FX5_CONTEXT_POOL_SIZE == 0
#error "FX5_CONTEXT_POOL_SIZE must be greater than zero"
#endif

/**
 * @def FX5_CLEAR_VALUES_ON_SET_REQUEST
 * @brief Controls whether fx5_set_request() clears the whole context value store.
 *
 * Enabled by default for deterministic behavior and stale-value protection.
 * Embedded builds that need to minimize CPU time may define this as 0 if the
 * application always initializes all write values before building a request.
 */
#ifndef FX5_CLEAR_VALUES_ON_SET_REQUEST
#define FX5_CLEAR_VALUES_ON_SET_REQUEST (1u)
#endif

#if FX5_CLEAR_VALUES_ON_SET_REQUEST != 0 && FX5_CLEAR_VALUES_ON_SET_REQUEST != 1
#error "FX5_CLEAR_VALUES_ON_SET_REQUEST must be 0 or 1"
#endif

/**
 * @def FX5_MAX_REQUEST_SIZE
 * @brief Maximum request frame size that may be generated by the library.
 *
 * Allocate at least this many bytes for the output buffer passed to
 * fx5_build_request().
 */
#define FX5_MAX_REQUEST_SIZE \
(FX5_REQ_TCP_HEADER_SIZE_4E + FX5_REQ_PDU_HEADER_SIZE + FX5_MAX_BIT_PAYLOAD_BYTES + FX5_IOBUF_GUARD_BYTES)


/** @brief Successful FX5 response code. */
#define FX5_RESPONSE_OK (0x0000u)

/** @brief Logical true representation for bit-oriented values. */
#define FX5_BIT_TRUE (0x00FFu)

/** @brief Logical false representation for bit-oriented values. */
#define FX5_BIT_FALSE (0x0000u)

/** @brief Maximum supported 24-bit FX5 device address. */
#define FX5_MAX_ADDRESS (0x00FFFFFFu)

/** @brief Maximum number of bytes that may be discarded during resynchronization. */
#define FX5_RESYNC_LIMIT (64u)

/**
 * @brief Supported FX5 device types.
 */
typedef enum {
    FX5_DEV_M  = 0x90, /**< Internal relay */
    FX5_DEV_SM = 0x91, /**< Special relay */
    FX5_DEV_L  = 0x92, /**< Latching relay */
    FX5_DEV_F  = 0x93, /**< Annunciator */
    FX5_DEV_S  = 0x98, /**< Step relay */
    FX5_DEV_X  = 0x9C, /**< Input relay */
    FX5_DEV_Y  = 0x9D, /**< Output relay */
    FX5_DEV_B  = 0xA0, /**< Link relay */
    FX5_DEV_SB = 0xA1, /**< Link special relay */
    FX5_DEV_D  = 0xA8, /**< Data register */
    FX5_DEV_SD = 0xA9, /**< Special register */
    FX5_DEV_W  = 0xB4, /**< Link register */
    FX5_DEV_SW = 0xB5  /**< Link special register */
} fx5_device_t;

/**
 * @brief Supported FX5 command codes.
 */
typedef enum {
    FX5_CMD_BATCH_WRITE = 0x1401, /**< Batch write */
    FX5_CMD_BATCH_READ  = 0x0401  /**< Batch read */
} fx5_cmd_t;

/**
 * @brief Supported SLMP binary header types.
 */
typedef enum {
    FX5_3E_HEADER = 0,      /**< 3E binary frame */
    FX5_4E_HEADER = 1,      /**< 4E binary frame */
    FX5_UNKNOWN_HEADER = 2  /**< Internal/parser helper value */
} fx5_header_t;


/**
 * @name Default network settings
 * @brief Default values used by fx5_network_settings_init() and context reset.
 *
 * These values correspond to a typical direct Ethernet connection to an FX5 PLC.
 * Users may override them after initialization if required.
 * @{
 */

/** Default frame type (4E recommended for new implementations) */
#define FX5_DEFAULT_HEADER_TYPE         FX5_4E_HEADER

/** Default network number */
#define FX5_DEFAULT_NETWORK_NO          0x00u

/** Default PC number */
#define FX5_DEFAULT_PC_NO               0xFFu

/** Default module I/O number */
#define FX5_DEFAULT_MODULE_IO_NO        0x03FFu

/** Default module station number */
#define FX5_DEFAULT_MODULE_STATION_NO   0x00u

/** Default monitoring timer (in units of 250 µs) */
#define FX5_DEFAULT_MONITORING_TIMER    0x0010u

/** @} */

/**
 * @brief Network and routing settings used for SLMP communication.
 *
 * Responses are parsed with automatic 3E/4E detection, but requests are built
 * according to the header type configured in the context.
 * Use fx5_network_settings_init() to initialize with default values (see @ref FX5_DEFAULT_HEADER_TYPE and related macros).
 */
typedef struct fx5_network_settings {
    fx5_header_t header_type;       /**< Outgoing request header format */
    uint8_t network_no;             /**< Network number */
    uint8_t pc_no;                  /**< PC number */
    uint16_t module_io_no;          /**< Destination module I/O number */
    uint8_t module_station_no;      /**< Destination module station number */
    uint16_t monitoring_timer;      /**< Monitoring timer for outgoing request */
} fx5_network_settings_t;

/**
 * @brief Library status and error codes.
 */
typedef enum {
    FX5_ST_OK = 0,              /**< Operation completed successfully */
    FX5_ST_ERR_NULL,            /**< Required pointer argument is NULL */
    FX5_ST_ERR_TOO_SMALL,       /**< Output or input buffer is too small */
    FX5_ST_ERR_NEED_MORE,       /**< More response bytes are required */
    FX5_ST_ERR_INVALID_ADDRESS, /**< Invalid device address */
    FX5_ST_ERR_INVALID_COUNT,   /**< Invalid value count */
    FX5_ST_ERR_INVALID_INDEX,   /**< Invalid value index */
    FX5_ST_ERR_UNSUPPORTED,     /**< Unsupported command, device, or mode */
    FX5_ST_ERR_INTERNAL,        /**< Internal consistency error */
    FX5_ST_ERR_RESYNC,          /**< Resynchronization limit exceeded */
    FX5_ST_ERR_HEADER_MISMATCH, /**< Parsed frame is incompatible with active transaction */
    FX5_ST_ERR_NO_CONTEXT,      /**< No free context available in internal pool */
    FX5_ST_ERR_NOT_ACQUIRED,    /**< Context is not acquired */
    FX5_ST_ERR_STATE,           /**< Invalid API usage for current internal state */
    FX5_ST_RESPONSE_ERROR       /**< PLC returned a non-zero response code */
} fx5_status_t;

/**
 * @brief Opaque FX5 context type.
 *
 * The actual structure definition is private to the implementation.
 */
typedef struct fx5_context fx5_context_t;

/**
 * @brief Acquire a context from the internal static pool.
 *
 * A successfully acquired context is reset to default state.
 *
 * @param[out] out_ctx Receives the acquired context handle.
 * @return FX5_ST_OK on success, FX5_ST_ERR_NO_CONTEXT if no free context exists,
 *         or FX5_ST_ERR_NULL if @p out_ctx is NULL.
 */
fx5_status_t fx5_acquire(fx5_context_t **out_ctx);


/**
 * @brief Release a previously acquired context back to the internal pool.
 *
 * This function returns the context to the internal pool and invalidates
 * the caller's pointer.
 *
 * The function expects a pointer to the context pointer (fx5_context_t **).
 * On successful release, the pointer is set to NULL to prevent accidental
 * reuse of a stale context.
 *
 * The context is internally reset before being returned to the pool,
 * ensuring that no residual state is visible to the next user.
 *
 * Calling this function with:
 * - ctx == NULL      → no effect
 * - *ctx == NULL     → no effect
 *
 * After this call, the context must not be used again unless it is
 * reacquired via fx5_acquire().
 *
 * Typical usage:
 * @code
 * fx5_context_t *ctx = NULL;
 * fx5_acquire(&ctx);
 *
 * // ... use ctx ...
 *
 * fx5_release(&ctx);
 * // ctx is now NULL
 * @endcode
 *
 * @param[in,out] ctx Pointer to the context pointer to release.
 */
void fx5_release(fx5_context_t **ctx);

/**
 * @brief Reset an acquired context to its default state.
 *
 * This clears request parameters, response data, internal receive buffer state,
 * serial tracking, and restores default network settings.
 *
 * @param[in] ctx Context handle.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_reset(fx5_context_t *ctx);


/**
 * @brief Initialize network settings with default values.
 *
 * Fills the given @p settings structure with library default values.
 * These defaults correspond to a typical direct Ethernet connection
 * to an FX5 PLC using SLMP protocol.
 *
 * The following fields are initialized:
 * - header_type           = @ref FX5_DEFAULT_HEADER_TYPE
 * - network_no            = @ref FX5_DEFAULT_NETWORK_NO
 * - pc_no                 = @ref FX5_DEFAULT_PC_NO
 * - module_io_no          = @ref FX5_DEFAULT_MODULE_IO_NO
 * - module_station_no     = @ref FX5_DEFAULT_MODULE_STATION_NO
 * - monitoring_timer      = @ref FX5_DEFAULT_MONITORING_TIMER
 *
 * The initialized settings can be modified by the caller before
 * applying them to a context.
 *
 * This function is also used internally during context initialization
 * and reset, ensuring consistent default configuration.
 *
 * @param[out] settings Pointer to the settings structure to initialize.
 * @return None. If @p settings is NULL, the function has no effect.
 */
void fx5_network_settings_init(fx5_network_settings_t *settings);


/**
 * @brief Set all network settings at once.
 *
 * @param[in] ctx Context handle.
 * @param[in] settings New network settings.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_set_network_settings(fx5_context_t *ctx,
                                      const fx5_network_settings_t *settings);

/**
 * @brief Read back the currently configured network settings.
 *
 * @param[in]  ctx Context handle.
 * @param[out] out_settings Receives the current network settings.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_get_network_settings(const fx5_context_t *ctx,
                                      fx5_network_settings_t *out_settings);

/**
 * @brief Set only the outgoing request header mode.
 *
 * @param[in] ctx Context handle.
 * @param[in] mode 3E or 4E binary header mode.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_set_header_mode(fx5_context_t *ctx,
                                 fx5_header_t mode);


/**
 * @brief Set the monitoring timer used in outgoing requests.
 *
 * @param[in] ctx Context handle.
 * @param[in] timer Monitoring timer value.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_set_monitoring_timer(fx5_context_t *ctx,
                                      uint16_t timer);

/**
 * @brief Configure the active request.
 *
 * This call sets the transaction command, target device, base address,
 * and logical value count. For write requests, individual payload values
 * may then be set with fx5_set_write_value().
 *
 * @p count is limited by @ref FX5_MAX_WORD_VALUE_COUNT for word devices and
 * @ref FX5_MAX_BIT_VALUE_COUNT for bit devices. These are library storage
 * limits caused by the fixed-size value array in each context. They should not
 * be interpreted as maximum batch sizes supported by the PLC or by SLMP.
 *
 * @param[in] ctx Context handle.
 * @param[in] command Command code.
 * @param[in] device Device type.
 * @param[in] address 24-bit FX5 device address.
 * @param[in] count Logical number of values to read or write.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_set_request(fx5_context_t *ctx,
                             fx5_cmd_t command,
                             fx5_device_t device,
                             uint32_t address,
                             uint16_t count);

/**
 * @brief Set a single write payload value at a given logical index.
 *
 * For word devices, one logical value corresponds to one transmitted word and
 * one storage slot. For bit devices, values are addressed by logical bit index
 * and packed internally; callers still pass:
 * - FX5_BIT_TRUE
 * - FX5_BIT_FALSE
 *
 * The builder packs bit values into the wire format internally.
 *
 * @param[in] ctx Context handle.
 * @param[in] index Logical write value index.
 * @param[in] value Value to store.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_set_write_value(fx5_context_t *ctx,
                                 uint16_t index,
                                 uint16_t value);

/**
 * @brief Build the currently configured request into a caller-provided buffer.
 *
 * The generated request uses the currently configured outgoing header mode
 * (3E or 4E).
 *
 * @param[in]  ctx Context handle.
 * @param[out] out_buf Output byte buffer.
 * @param[in]  out_buf_size Size of @p out_buf in bytes.
 * @param[out] actual_size Receives the generated request size.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_build_request(fx5_context_t *ctx,
                               uint8_t *out_buf,
                               uint16_t out_buf_size,
                               uint16_t *actual_size);

/**
 * @brief Feed received response bytes into the context's internal RX buffer.
 *
 * This function may be called repeatedly as bytes arrive from TCP.
 *
 * @param[in] ctx Context handle.
 * @param[in] data Input byte buffer.
 * @param[in] size Number of bytes to append.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_feed_response_bytes(fx5_context_t *ctx,
                                     const uint8_t *data,
                                     uint16_t size);

/**
 * @brief Attempt to parse one complete response from the internal RX buffer.
 *
 * The parser automatically detects 3E and 4E response headers and performs
 * stream resynchronization if needed.
 *
 * If a full valid frame is not yet available, FX5_ST_ERR_NEED_MORE is returned.
 * On success, parsed values and response metadata become available through
 * the response getter functions.
 *
 * @param[in] ctx Context handle.
 * @return FX5_ST_OK on success, or an error code on failure.
 */
fx5_status_t fx5_parse_response(fx5_context_t *ctx);

/**
 * @brief Get the PLC response code from the last successfully parsed frame.
 *
 * @param[in] ctx Context handle.
 * @return PLC response code. If no valid response has been parsed yet,
 *         the returned value is implementation-defined.
 */
uint16_t fx5_get_response_code(const fx5_context_t *ctx);

/**
 * @brief Get the number of logical response values from the last parsed frame.
 *
 * @param[in] ctx Context handle.
 * @return Number of available logical response values.
 */
uint16_t fx5_get_response_count(const fx5_context_t *ctx);

/**
 * @brief Read a single parsed response value by index.
 *
 * @param[in]  ctx Context handle.
 * @param[in]  index Logical response value index.
 * @param[out] out_value Receives the value.
 * @return FX5_ST_OK on success, FX5_ST_ERR_INVALID_INDEX if the index is out of range,
 *         or another error code on failure.
 */
fx5_status_t fx5_get_response_value(const fx5_context_t *ctx,
                                    uint16_t index,
                                    uint16_t *out_value);

/**
 * @brief Get the last transmitted 4E serial number associated with the context.
 *
 * For 3E outgoing requests this value is typically zero.
 *
 * @param[in] ctx Context handle.
 * @return Last transmitted serial number.
 */
uint16_t fx5_get_last_serial(const fx5_context_t *ctx);

#ifdef __cplusplus
}
#endif

/** @} */

#endif /* FX5_H */
